# fly.toml app configuration file generated for volante-backend on 2024-10-23T08:42:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'volante-backend'
primary_region = 'gru'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[checks]
  [checks.healthcheck]
  grace_period = "30s"
  interval = "15s"
  method = "get"
  path = "/"
  port = 8080
  timeout = "10s"
  type = "http"